/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'cgrass' at '12/25/16 10:52 AM' with Gradle 2.14.1
 *
 * @author cgrass, @date 12/25/16 10:52 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
